### ISSUE TITLE
xrankmirrors & xchangemirrors license?

### ISSUE THREAD

**Issue by KF-Art** [wael444/dotfiles#2]
Greetings, I've found your `xrankmirrors` and `xchangemirrors` scripts from Reddit.
I'm part of Cereus Linux team (Void derivative), and  we're interested on this functionality to allow user to change both Void and Cereus mirrors easily, so this would be a great base for our plans. But I was wondering what license do they have. This is important, because we want to do everything in the right way. Thanks in advance.

**Comment by wael444** [comment]
The script themselves are not licensed, xrankmirrors was actually done already by another script and I just managed to do the same thing it did albeit simpler or better. Do what you want with the scripts (credit me tho :3c) I suggest taking a look and rewriting or making them better because my scripting sucks.

The scripts are in the `old` branch of my dotfiles, due to me not using void anymore.

**Comment by KF-Art** [comment]
Thank you, we'll crediting you when forking.
Have a great day!

**Comment by wael444** [comment]
also, since you are going to make a Void fork, i have suggestions that you should probably ignore but i was always looking to see in a void fork i wanted to originally make but i just didn't work on it.
1. POSIX compliancy, allow the user to switch any core utilities and shell, meaning that the void-packages is not posix compliant and is huge as is, look at `xbps-create`, its not hard to make your own package creator for XBPS.
2. thats it
